# Run rubocop --auto-gen-config to generate a to-do file with a list of issues
#

AllCops:
  TargetRubyVersion: 2.2
  Include:
    - Rakefile
    - config.ru
    - lib/**/*
  Exclude:
    - db/schema.rb
    - db/**/*
    - files/**/*
    - test/**/*
    - spec/**/*
    - tmp/**/*
    - bin/**/*
    - !ruby/regexp /old_and_unused\.rb$/
    - lib/templates/erb/scaffold/_form.html.erb
    - scripts/interactive/**/*
  # By default, the rails cops are not run. Override in project or home
  # directory .rubocop.yml files, or by giving the -R/--rails option.
  # RunRailsCops: true

# Disable documentation checking until a class needs to be documented
Documentation:
  Enabled: false

Style/IndentationWidth:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/LineLength:
  Max: 100

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 25

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 12

Metrics/AbcSize:
  Max: 28

Style/ClassVars:
  Exclude:
    - 'lib/encrypt_column/encrypt_column.rb'

