inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Include:
    - Rakefile
    - config.ru
    - lib/**/*
  Exclude:
    - db/schema.rb
    - db/**/*
    - files/**/*
    - test/**/*
    - spec/**/*
    - tmp/**/*
    - bin/**/*
    - !ruby/regexp /old_and_unused\.rb$/
    - lib/templates/erb/scaffold/_form.html.erb
    - scripts/interactive/**/*
